In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#pip install pandas

In [ ]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights = np.random.randn(3)*1e-4
        print(f"Initial weights before training : {self.weights}")
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self,inputs,weights):
        z = np.dot(inputs,weights)
        return np.where(z>0,1,0)

    def fit(self,X,y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"X_with_bias : {X_with_bias}")

        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch :{epoch}")
            print("--"*10)

            y_hat = self.activationFunction(X_with_bias,self.weights)
            print(f"redicted_values after forword pass:\n{y_hat}")

            self.error = self.y - y_hat
            print(f"error : {self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)

            print(f"updated weights after epoch : \n{epoch}/{self.epochs}:\n{self.weights}")
            print("####"*10)


    def predict(self,X):
        X_with_bias = np.c_[self.X,-np.ones((len(X),1))]
        return self.activationFunction(X_with_bias,self.weights)

    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"total loss : {total_loss}")
        return total_loss



In [ ]:
def prepare_data(df):
    print(df)
    X_prepare = df.drop('y',axis = 1)
    y_prepare = df['y']

    return X_prepare,y_prepare

In [ ]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}
df = pd.DataFrame(AND)

In [ ]:
df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
df['y']

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [ ]:
X,y = prepare_data(df)
ETA = 0.3
EPOCHS = 10
model = Perceptron(eta = ETA, epochs = EPOCHS)
model.fit(X,y)

_ = model.total_loss()

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1
Initial weights before training : [-1.15995326e-04 -9.60344746e-05 -8.23774938e-05]
X_with_bias : [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch :0
--------------------
redicted_values after forword pass:
[1 0 0 0]
error : 0   -1
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch : 
0/10:
[ 2.99884005e-01  2.99903966e-01 -8.23774938e-05]
########################################
--------------------
for epoch :1
--------------------
redicted_values after forword pass:
[1 1 1 1]
error : 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch : 
1/10:
[-1.15995326e-04 -9.60344746e-05  8.99917623e-01]
########################################
--------------------
for epoch :2
--------------------
redicted_values after forword pass:
[0 0 0 0]
error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch : 
2/10:
[0.299